import re

with open('src/App.tsx', 'r') as f:
    content = f.read()

missing_keys = [
    "Chưa có Landing Page nào. Hãy tạo mới và chọn Loại Liên Kết là \"Landing Page\"!",
    "Liên kết phát nhạc",
    "Demo",
    "Mật khẩu chung",
    "để nghe tự do mọi album/bài hát bị khóa mà không cần nhập mật khẩu.",
    "Đang khôi phục...",
    "Giao diện xem trên máy tính",
    "Nhập link bài hát ngoài hệ thống",
    "Đã gửi báo cáo thành công!",
    "Tìm kiếm...",
    "Ảnh quá lớn",
    "Thùng rác tạm thời",
    "Mật khẩu mới phải từ 4 ký tự trở lên!",
    "Có lỗi xảy ra khi tạo playlist.",
    "Logo đối tác (Upload)",
    "Có lỗi xảy ra khi dịch thuật!",
    "Tên bài hát",
    "Từ chối yêu cầu",
    "Tiêu đề Website",
    "Thiết Lập Mật Khẩu Thành Viên",
    "Chỉnh sửa cấu hình",
    "Hộp thư",
    "Khôi phục bản cũ",
    "Hành động",
    "Phần mở rộng (Link bài hát)",
    "mà không cần nhập passcode riêng biệt.",
    "Xóa",
    "bài nhạc",
    "canvas",
    "Chưa có bài hát thương hiệu nào. Hãy tạo mới và đánh dấu \"Nhạc Thương Hiệu\"!",
    "Đang dùng",
    "Lỗi",
    "Khôi phục phiên bản nhạc thành công!",
    "Tạo playlist thành công!",
    "Đã di chuyển bài hát vào Thùng rác!",
    "Dung lượng file nhạc quá lớn (",
    "10 mục",
    "isBrand', isBrand ? 'true' : 'false",
    "Lỗi kết nối: ",
    "✓ Bài hát đã phát hành sẽ không sử dụng mật khẩu bảo vệ.",
    "Tải tệp thất bại",
    "Chưa rõ",
    "Chọn bìa đĩa",
    "isDraft', isDraft ? 'true' : 'false",
    "Vui lòng đợi ảnh bìa tải lên xong!",
    "Mật khẩu chung cho các Demo",
    "meta",
    "Ảnh Nền (Nếu có)",
    "Favicon (Icon trên trình duyệt)",
    "Gửi báo cáo",
    "Thêm đã chọn",
    "Dịch thuật thành công! Toàn bộ thông tin hồ sơ và danh sách nhạc đã được dịch sang tất cả ngôn ngữ.",
    "Chưa có bài hát đã phát hành nào. Hãy tạo mới và đặt trạng thái \"Ra rồi\"!",
    "Xác nhận tạo mới",
    "Đã di chuyển playlist vào Thùng rác!",
    "Chưa có bản nháp nào. Bản nháp được lưu từ màn hình tạo hoặc chỉnh sửa bài hát!",
    "Quản lý",
    "Bìa Đĩa Chỉnh Sửa (Dùng làm thumbnail)",
    "Chọn Playlist",
    "Giờ đây bạn có thể thưởng thức toàn bộ album, danh sách phát và các bài hát đệm demo bảo mật trên hệ thống của",
    "Mở lại yêu cầu",
    "Đang lưu...",
    "status', statusEl?.value || 'public",
    "Xóa playlist",
    "Mật khẩu mới",
    "Không tìm thấy bài hát nào",
    "song",
    "Đăng bài hát thành công!",
    "Bỏ trống nếu không cần",
    "MB). Vui lòng tải lên file nhạc dưới 100MB để đảm bảo tốc độ xử lý của server.",
    "Có lỗi xảy ra khi kiểm tra bài hát!",
    "Người yêu cầu:",
    "Mặc định: Album/EP",
    "Lỗi tải thông tin quản trị:",
    "Sáng tác",
    "Thêm vào Playlist",
    "Views YouTube",
    "VD: 10M, Dành cho hiệu ứng TikTok...",
    "Nhập lời bài hát chỉnh sửa (nếu có)...",
    "Link Google Drive tải nhạc",
    "Nhập lời bài hát mới (nếu có)...",
    "Vui lòng đợi ảnh nền tải lên xong!",
    "Nhập link YouTube Music....",
    "Tiêu đề",
    "Nhập link Apple Music...",
    "Nếu nhập link, người dùng sẽ thấy icon tải nhạc (Download) ở trên phần lời bài hát để click tải.",
    "bài hát",
    "Là nhạc thương hiệu (Brand Music)",
    "Kéo thả các dòng bài hát để sắp xếp thứ tự hiển thị ưu tiên ngoài trang chủ",
    "Lưu cài đặt",
    "Mật khẩu thành viên",
    "Vui lòng đợi trong giây lát. Hệ thống đang tối ưu hóa dữ liệu và lưu trữ an toàn trên cloud.",
    ") thay vì sử dụng địa chỉ mặc định của hệ thống.",
    "Ngôn ngữ mặc định (Default Language)",
    "Kéo thả bìa đĩa trực tiếp vào ô này",
    "Loại thành tích",
    "Bạn có chắc muốn hủy yêu cầu này?",
    "Nhập tên playlist (ví dụ: Album Vol. 1, Single...)",
    "Đã reset Secret Link thành công!",
    "Gửi yêu cầu gỡ hoặc chỉnh sửa cho bài hát này",
    "Cấu hình tên miền riêng (Custom Domain)",
    "Avatar Nghệ Sĩ",
    "Thêm bài hát",
    "Tab 1 (Nhạc phát hành)",
    "Lỗi tải lên bài hát!",
    "Chỉnh sửa",
    "Sẽ tự động hiển thị 4 bài hát mới nhất từ playlist này.",
    "Xóa khỏi danh sách đăng lại",
    "Tên đối tác",
    "Tạo Playlist Mới",
    "Firestore Database ID (mặc định là default)",
    "hoặc",
    "Đổi Mật Khẩu Quản Trị (Admin)",
    "Lỗi kết nối",
    "Bạn đã đăng nhập thành công dưới quyền",
    "Hộp hội thoại trống",
    "Yêu cầu gỡ",
    "Chọn",
    "Hệ thống sẽ giữ tạm thời các mục trên tại đây tối đa 30 ngày. Quá thời gian này, các mục sẽ bị dọn dẹp và xóa vĩnh viễn không thể khôi phục.",
    "Chưa tạo Secret Link cho Playlist này.",
    "Đã copy Secret Link!",
    "Mạng xã hội",
    "Danh sách bài hát (Kéo thả để sắp xếp)",
    "Tên gợi nhớ (VD: DB cũ, Mặc định...)",
    "Có lỗi xảy ra khi kết nối máy chủ.",
    "Hiển thị (Trạng thái phát hành)",
    "Vui lòng điền đầy đủ các trường!",
    "VD: nghesi.com",
    "Lưu thay đổi",
    "Thông tin hồ sơ",
    "Chưa có bài hát demo nào. Hãy tạo mới và đặt trạng thái \"Đề mô\"!",
    "50 mục",
    "Thay đổi",
    "Chọn ảnh nền",
    "Hãy chọn bài hát để xem.",
    "Đã tạo bản sao thành công! Đang chuyển hướng...",
    "Đã copy link playlist!",
    "Trang chủ",
    "Thêm video",
    "streams",
    "Vai trò của bạn",
    "Đóng",
    "Làm mới DB này",
    "Góp ý tính năng",
    "Secret Link (Chia sẻ trực tiếp xem không hỏi mật khẩu)",
    "Để trống nếu không muốn dùng mật khẩu chung",
    "token",
    "Trực Tiếp",
    "Phần mở rộng (Sub-domain)",
    "Chưa có playlist nào. Hãy tạo mới một playlist bên trên!",
    "20 bài",
    "Bạn có chắc muốn làm mới toàn bộ Secret Link? Các Secret Link cũ sẽ không còn hoạt động, tự động chuyển về đường dẫn gốc yêu cầu mật khẩu.",
    "Tiếng Việt",
    "Mật khẩu mới (tối thiểu 4 ký tự)",
    "Landing Page / Điều hướng",
    "💡 Lưu ý:",
    "Xác nhận xóa đăng lại",
    "Thùng rác",
    "Xem giao diện điện thoại",
    "Cập nhật mật khẩu thành viên thành công!",
    "extension",
    "Khu Vực Thành Viên",
    "Sử dụng tên miền riêng của bạn (ví dụ:",
    "Tố cáo bài viết vi phạm.",
    "Chỉnh sửa playlist",
    "Xem giao diện máy tính",
    "Lỗi kết nối.",
    "Ẩn khỏi danh sách nghệ sĩ trên trang chủ Chorus.vn",
    "Đăng lại bài hát này lên kênh của bạn",
    "Vui lòng đợi file nhạc tải lên xong!",
    "Đã copy link bài hát!",
    "Tạo, sắp xếp thứ tự ưu tiên và chỉnh sửa danh sách phát nhạc",
    "Để trống sẽ dùng mặc định: Thiên Đường Demo của [Tên nghệ sĩ]",
    "Chọn Template",
    "Năm phát hành",
    "Đang xuất bản...",
    "Yêu cầu ban đầu:",
    "Bạn có chắc chắn gỡ bài hát này khỏi trang của mình theo yêu cầu của đối tác không?",
    "Bạn có chắc chắn muốn xóa bài hát ngoài này khỏi danh sách Đăng lại?",
    "Lỗi tải file. Vui lòng thử lại.",
    "Đang tải dữ liệu bài hát...",
    "Bởi:",
    "Giá trị / Nội dung chi tiết",
    "Lỗi khi duplicate bản ghi.",
    "Nhập tin nhắn trao đổi...",
    "Bài viết ra rồi",
    "Chia sẻ Link",
    "Kiểm tra & Thêm",
    "Lưu Bản Nháp",
    "Gửi báo cáo / yêu cầu gỡ hoặc chỉnh sửa",
    "Gửi feedback thất bại",
    "Mô tả lý do / Nội dung chi tiết",
    "Xác nhận hủy yêu cầu",
    "Báo cáo tài khoản",
    "Top Trending YouTube",
    "Nội dung mô tả",
    "100 bài",
    "30 ngày",
    "Vui lòng truy cập trang quản lý tên miền của bạn (ví dụ: Cloudflare, GoDaddy, Nhân Hòa...) và thiết lập bản ghi sau để kết nối tên miền này:",
    "Cài Đặt",
    "Đã copy link!",
    "Kéo thả để sắp xếp lại thứ tự hiển thị của giao diện khi chọn. Nhấn vào Giao Diện để chỉnh sửa chi tiết.",
    "Thất bại",
    "Đang yêu cầu đổi thành:",
    "Xác nhận gỡ bài",
    "Ảnh bìa Playlist (Kích thước vuông)",
    "2d",
    "Mặc định: Đề Mô",
    "Lỗi cập nhật. Thử tải lại trang và làm lại!",
    "Bài Hát",
    "Nhập tên bài hát mới...",
    "Tên playlist",
    "Chào Mừng Thành Viên!",
    "Ca sĩ",
    "Xem trước giao diện",
    "Lỗi không xác định",
    "Tất cả các link ở trang chủ nếu chưa đặt mật khẩu riêng thì sẽ được bảo vệ bởi mật khẩu chung này.",
    "Các mục trong thùng rác",
    "Tạo Link Mới",
    "Đang xử lý",
    "Đã lưu thành công!",
    "Tự sinh Ngẫu Nhiên",
    "Giá trị (Points to)",
    "Tên (Host)",
    "Loại feedback",
    "Mô tả cụ thể và chi tiết ý kiến hoặc lỗi bạn gặp phải...",
    "Đã có lỗi xảy ra!",
    "trending",
    "Bạn có chắc chắn muốn mở lại ticket này không?",
    "Danh sách cuộc hội thoại",
    "📋 Hướng dẫn cấu hình DNS",
    "Vui lòng nhập thông tin đăng nhập quản trị",
    "Thành viên VIP",
    "Danh sách Playlist",
    "10 mục",
    "20 mục",
    "50 mục",
    "100 mục",
    "10 bài",
    "20 bài",
    "50 bài",
    "100 bài",
    "Không thể gửi tin nhắn: ",
    "Vui lòng kiểm tra lại!"
]

# We will just write all of these as identical keys/values for vi.
# And for en, we will provide some basic English translations or just default them so they exist and we can update them manually if needed.

# Wait, in the code, `useAdminTranslation` has a fallback:
# if (generalDict[trimmed]) return generalDict[trimmed];
# return trimmed;
# 
# So if a key doesn't exist, it RETURNS THE ORIGINAL VIETNAMESE STRING!
# That means if we just put the English translations for what we know, it will work.

translations_to_inject = {
    "Danh sách Playlist": "Playlist List",
    "Tạo, sắp xếp thứ tự ưu tiên và chỉnh sửa danh sách phát nhạc": "Create, arrange priority, and edit playlists",
    "10 mục": "10 items",
    "20 mục": "20 items",
    "50 mục": "50 items",
    "100 mục": "100 items",
    "10 bài": "10 songs",
    "20 bài": "20 songs",
    "50 bài": "50 songs",
    "100 bài": "100 songs",
    "Hiển thị": "Show",
    "Tìm kiếm...": "Search...",
    "Chào Mừng Thành Viên!": "Welcome Member!",
    "Khu Vực Thành Viên": "Member Area",
    "Vui lòng nhập thông tin đăng nhập quản trị": "Please enter admin login info",
    "Bạn đã đăng nhập thành công dưới quyền": "You have logged in successfully as",
    "Thành viên VIP": "VIP Member",
    "Giờ đây bạn có thể thưởng thức toàn bộ album, danh sách phát và các bài hát đệm demo bảo mật trên hệ thống của": "You can now enjoy all albums, playlists, and secure demo backing tracks on the system of",
    "mà không cần nhập passcode riêng biệt.": "without needing a separate passcode."
}

def inject_to_lang(lang_code, lang_content, translations):
    # Find the last `  },` in this block
    # Actually just add to the end of the block.
    # The block usually ends with some key-value pair and then `  },`
    lines = lang_content.split('\n')
    
    # Let's just create the extra lines
    extra = []
    for k, v in translations.items():
        # Escape quotes
        k = k.replace('"', '\\"')
        v = v.replace('"', '\\"')
        extra.append(f'    "{k}": "{v}",')
        
    # we can append it at the beginning of the block to be safe.
    # block starts with `  en: {`
    # Let's just insert it right after the brace.
    return "{\n" + "\n".join(extra) + "\n" + lang_content[1:]

new_content = content
for lang in ['vi', 'en', 'ko', 'ja', 'th', 'zh']:
    # The regex to find each block inside adminTranslations
    # Let's find `lang: {`
    pattern = rf"(?m)^  {lang}: {{"
    
    # We will inject right after `lang: {`
    extra = []
    for k, v in translations_to_inject.items():
        k = k.replace('"', '\\"')
        v_to_use = v if lang == 'en' else k  # For now just map to same or known for EN
        extra.append(f'    "{k}": "{v_to_use}",')
        
    replacement = f"  {lang}: {{\n" + "\n".join(extra)
    new_content = re.sub(pattern, replacement, new_content, count=1)
    
with open('src/App.tsx', 'w') as f:
    f.write(new_content)
